### PR TITLE
config: load slugify extension and use for project_shortname

### PR DESCRIPTION
**Pull request by ppanero**
~~Requires: https://github.com/inveniosoftware/invenio-cli/pull/123~~ Comes from upstream cookiecutter.

Sample result:

```
% cookiecutter ../cookiecutter-invenio-rdm 
project_name [My Site]: Pablo's version
project_shortname [pablo-s-version]: 
project_site [pablo-s-version.com]: 
github_repo [pablo-s-version/pablo-s-version]: 
description [Invenio RDM Pablo's version Instance]: 
author_name [CERN]: 
author_email [info@pablo-s-version.com]: 
```

Closes: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/45

### CODE REVIEW

**Comment by ppanero** [comment]
@fenekku yes, it does:

```python
>>> slugify(" a test ")
'a-test'
```

It also lowercases, so we would only need ``cookiecutter.project_name | slugify ``.

I'd close this PR and we open an issue to put the filter once is released. WDYT?

**Comment by fenekku** [comment]
@ppanero That's great for the included trimming. What about just leaving this PR open and updating the branch with the changes when cookiecutter is released? I would say to keep the https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/45 issue open rather than create a new one. We will close it once this PR has the changes to close it. That works?

**Comment by ppanero** [comment]
Yup, lets leave it open :)

**Comment by ppanero** [comment]
@fenekku I have updated the PR, this has been released already in the upstream cookiecutter library 🚀 

Tested the input/output of the description. It works as expected with `Pablo's version` :)

**Comment by ppanero** [comment]
@fenekku rebased, waiting for travis :)

**Pull request merged**
